"""Find duplicated, redundant and unreferenced model files. Reports only -- never deletes.

Four questions, answered separately because they carry very different risk:

1. **Byte-identical duplicates.** Same size, then same fingerprint, then same full hash. Deleting
   all but one is safe by construction.
2. **Variant families.** The same model held in several quantizations (`_bf16`, `_fp8`,
   `_w4a4_convrot`, `-int8-convrot`, `Q5_K_M`, ...). Not duplicates -- a judgement call, but this
   is usually where the space actually is.
3. **Not referenced by any saved workflow.** Every JSON under the workflow and blueprint folders is
   scanned for strings that look like model filenames. A file nobody references is a *candidate*,
   not proof: nodes build paths at runtime, and workflows live outside this folder too.
4. **Outputs produced by this project.** Conversions made here, listed separately because deleting
   them destroys nothing original and they can be regenerated by the converter.

Hashing is cheap by design: only files that share an exact size with another file are fingerprinted
(first and last 1 MiB plus the size), and a full SHA-256 runs only when fingerprints collide.

Nothing is removed. With `--emit-script` it writes a shell script of deletions for you to read and
run yourself; the script is never executed here.

    python tools/model_audit.py --report audit.json --emit-script cleanup.sh
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

PORTABLE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PORTABLE_ROOT / "ComfyUI"))

MODEL_SUFFIXES = {".safetensors", ".gguf", ".ckpt", ".pt", ".pth", ".bin", ".onnx", ".sft"}
CHUNK = 1024 * 1024

# Stripped when grouping variants of one model. Order matters: longest first.
QUANT_MARKERS = [
    "_w4a4_convrot", "-w4a4-convrot", "_w4a8_mixed", "_w4a8", "-w4a8", "_w4a16", "-w4a16",
    "-comfy-int8-convrot", "_int8_convrot", "-int8-convrot", "_nvfp4_awq", "-nvfp4", "_nvfp4",
    "_fp8_e4m3fn", "_fp8_scaled", "-fp8", "_fp8", "_smooth", "_convrot",
    "-bf16", "_bf16", "-fp16", "_fp16", "_fp32", "-fp32", "_pruned", "-pruned", "_scaled",
    "_mixed", "-mixed",
]
GGUF_QUANT = re.compile(r"[-_](?:Q\d+_[KM0-9_]*|IQ\d+_\w+|F16|F32|BF16)$", re.IGNORECASE)
# Files this project produced; safe to delete because the converter can remake them.
# Kept in step with what the converters actually write, which is not automatic: `quant_mixed.py`
# writes `{stem}_mixed.safetensors` and `to_native.py` writes `{stem}_native.safetensors`, and
# neither was listed. The consequence is not cosmetic -- an unlisted output falls into the
# "largest files no workflow mentions" bucket, which is the list a user reads looking for things
# to delete, instead of into "regenerable".
PROJECT_OUTPUT = re.compile(
    r"_(w4a4_convrot|w4a8|w4a8_mixed|w4a4_smooth|w4a4_g\d+|int8|int8_convrot|mixed|native)"
    r"\.safetensors$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", action="append", default=[],
                        help="extra directory to scan; defaults to ComfyUI's configured folders")
    parser.add_argument("--min-mb", type=float, default=64.0,
                        help="ignore files smaller than this")
    parser.add_argument("--skip-network", action="store_true",
                        help="skip UNC/mapped-network roots, which are slow to fingerprint")
    parser.add_argument("--report", type=Path)
    parser.add_argument("--emit-script", type=Path,
                        help="write a reviewable deletion script for the byte-identical duplicates "
                             "only; it is never run from here")
    return parser.parse_args()


def human(size: float) -> str:
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if size < 1024 or unit == "TiB":
            return f"{size:.2f} {unit}"
        size /= 1024
    raise AssertionError


def model_roots(args: argparse.Namespace) -> list[Path]:
    import folder_paths

    extra = PORTABLE_ROOT / "ComfyUI" / "extra_model_paths.yaml"
    if extra.is_file():
        from utils.extra_config import load_extra_path_config

        load_extra_path_config(str(extra))

    roots: list[Path] = []
    for name in folder_paths.folder_names_and_paths:
        for path in folder_paths.get_folder_paths(name):
            candidate = Path(path)
            if candidate.is_dir():
                roots.append(candidate.resolve())
    roots += [Path(r).resolve() for r in args.root]

    unique: list[Path] = []
    for root in sorted(set(roots), key=lambda p: len(str(p))):
        if any(str(root).startswith(str(seen) + os.sep) or root == seen for seen in unique):
            continue
        unique.append(root)
    return unique


def fingerprint(path: Path, size: int) -> str:
    digest = hashlib.blake2b(str(size).encode(), digest_size=16)
    with path.open("rb") as handle:
        digest.update(handle.read(CHUNK))
        if size > 2 * CHUNK:
            handle.seek(-CHUNK, os.SEEK_END)
            digest.update(handle.read(CHUNK))
    return digest.hexdigest()


def full_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(8 * CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def normalize(stem: str) -> str:
    """Collapse quantization markers so variants of one model land in the same family."""
    lowered = GGUF_QUANT.sub("", stem)
    changed = True
    while changed:
        changed = False
        for marker in QUANT_MARKERS:
            if lowered.lower().endswith(marker):
                lowered, changed = lowered[: -len(marker)], True
    return lowered.strip("-_ ").lower()


def referenced_names(search_dirs: list[Path]) -> set[str]:
    """Every model-looking filename mentioned in any workflow or blueprint JSON."""
    pattern = re.compile(r"[\w\-. ()\[\]]+\.(?:safetensors|gguf|ckpt|pt|pth|bin|onnx|sft)",
                         re.IGNORECASE)
    found: set[str] = set()
    for directory in search_dirs:
        if not directory.is_dir():
            continue
        for path in directory.rglob("*.json"):
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for match in pattern.findall(text):
                found.add(Path(match.replace("\\", "/")).name.lower())
    return found


def main() -> int:
    args = parse_args()
    roots = model_roots(args)
    minimum = int(args.min_mb * 1024 * 1024)

    files: list[dict] = []
    for root in roots:
        network = str(root).startswith("\\\\") or str(root).startswith("//")
        for path in root.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in MODEL_SUFFIXES:
                continue
            try:
                size = path.stat().st_size
            except OSError:
                continue
            if size < minimum:
                continue
            files.append({"path": path, "size": size, "root": root, "network": network})
    files.sort(key=lambda f: -f["size"])
    total = sum(f["size"] for f in files)
    print(f"{len(files)} model files across {len(roots)} roots, {human(total)}\n", flush=True)

    # 1. byte-identical duplicates
    by_size: dict[int, list[dict]] = defaultdict(list)
    for entry in files:
        by_size[entry["size"]].append(entry)
    candidates = [group for group in by_size.values() if len(group) > 1]
    duplicate_groups = []
    if candidates:
        print(f"fingerprinting {sum(len(g) for g in candidates)} same-size files "
              f"in {len(candidates)} groups", flush=True)
    for group in candidates:
        if args.skip_network and any(e["network"] for e in group):
            continue
        by_print: dict[str, list[dict]] = defaultdict(list)
        for entry in group:
            try:
                by_print[fingerprint(entry["path"], entry["size"])].append(entry)
            except OSError:
                continue
        for same in by_print.values():
            if len(same) < 2:
                continue
            by_hash: dict[str, list[dict]] = defaultdict(list)
            for entry in same:
                by_hash[full_hash(entry["path"])].append(entry)
            for digest, identical in by_hash.items():
                if len(identical) > 1:
                    duplicate_groups.append({
                        "sha256": digest, "size": identical[0]["size"],
                        "reclaimable": identical[0]["size"] * (len(identical) - 1),
                        "paths": [str(e["path"]) for e in identical],
                    })

    # 2. variant families
    families: dict[str, list[dict]] = defaultdict(list)
    for entry in files:
        families[normalize(entry["path"].stem)].append(entry)
    variant_families = sorted(
        ({"family": key, "total": sum(e["size"] for e in group),
          "largest": max(e["size"] for e in group),
          "members": [{"path": str(e["path"]), "size": e["size"]}
                      for e in sorted(group, key=lambda e: -e["size"])]}
         for key, group in families.items() if len(group) > 1),
        key=lambda f: -(f["total"] - f["largest"]))

    # 3. unreferenced
    referenced = referenced_names([
        PORTABLE_ROOT / "ComfyUI" / "user" / "default" / "workflows",
        PORTABLE_ROOT / "ComfyUI" / "blueprints",
        PORTABLE_ROOT / "ComfyUI" / "user" / "default" / "ComfyUI-Manager",
    ])
    unreferenced = [{"path": str(e["path"]), "size": e["size"]}
                    for e in files if e["path"].name.lower() not in referenced]

    # 4. this project's own outputs
    outputs = [{"path": str(e["path"]), "size": e["size"]}
               for e in files if PROJECT_OUTPUT.search(e["path"].name)]

    dup_bytes = sum(g["reclaimable"] for g in duplicate_groups)
    family_bytes = sum(f["total"] - f["largest"] for f in variant_families)
    unref_bytes = sum(u["size"] for u in unreferenced)
    output_bytes = sum(o["size"] for o in outputs)

    print(f"\n{'=' * 74}")
    print(f"1. byte-identical duplicates   {len(duplicate_groups):>4} groups   "
          f"{human(dup_bytes):>12} reclaimable  (safe)")
    print(f"2. variant families            {len(variant_families):>4} families "
          f"{human(family_bytes):>12} if only the largest is kept  (judgement)")
    print(f"3. unreferenced by workflows   {len(unreferenced):>4} files    "
          f"{human(unref_bytes):>12}  (candidates, not proof)")
    print(f"4. outputs made by this project{len(outputs):>4} files    "
          f"{human(output_bytes):>12}  (regenerable)")

    for title, rows in (("byte-identical duplicates", duplicate_groups[:10]),):
        if rows:
            print(f"\n--- {title} ---")
            for group in rows:
                print(f"  {human(group['reclaimable']):>10} reclaimable")
                for path in group["paths"]:
                    print(f"      {path}")

    if variant_families:
        print("\n--- largest variant families ---")
        for family in variant_families[:12]:
            print(f"  {family['family']}   {human(family['total'])} total, "
                  f"{human(family['total'] - family['largest'])} beyond the largest")
            for member in family["members"]:
                print(f"      {human(member['size']):>10}  {Path(member['path']).name}")

    if unreferenced:
        print("\n--- largest files no workflow mentions ---")
        for entry in sorted(unreferenced, key=lambda e: -e["size"])[:20]:
            print(f"  {human(entry['size']):>10}  {entry['path']}")

    if args.report:
        args.report.write_text(json.dumps({
            "roots": [str(r) for r in roots], "file_count": len(files), "total_bytes": total,
            "duplicates": duplicate_groups, "variant_families": variant_families,
            "unreferenced": sorted(unreferenced, key=lambda e: -e["size"]),
            "project_outputs": outputs,
            "reclaimable": {"duplicates": dup_bytes, "variants_beyond_largest": family_bytes,
                            "unreferenced": unref_bytes, "project_outputs": output_bytes},
        }, indent=2), encoding="utf-8")
        print(f"\nWrote {args.report}")

    if args.emit_script and duplicate_groups:
        lines = ["#!/bin/sh",
                 "# Byte-identical duplicates only. Read this before running it.",
                 "# The first path in each group is KEPT; the rest are removed.", ""]
        for group in duplicate_groups:
            lines.append(f"# sha256 {group['sha256'][:16]}  {human(group['size'])} each")
            lines.append(f"#   keep: {group['paths'][0]}")
            for path in group["paths"][1:]:
                lines.append(f'rm -i "{path}"')
            lines.append("")
        args.emit_script.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {args.emit_script} -- review it; nothing was deleted here")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
